version: "3.9"
services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller:latest
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
      - TZ=${TZ}
    volumes:
      - ${DOCKERDATADIR}/unifi-controller/config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '8443:8443'
      - '3478:3478/udp'
      - '10001:10001/udp'
      - '8080:8080'
      - '1900:1900/udp' #optional
      - '8843:8843' #optional
      - '8880:8880' #optional
      - '6789:6789' #optional
      - '5514:5514/udp' #optional
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 192.168.20.4
networks:
  default:
    external: true
    name: macvlan-network
